# Generated by Django 2.2.8 on 2020-04-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='put_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
